import 'package:flutter/material.dart';

class  StringsUtils {

  StringsUtils._();

  static ValueNotifier<int> bottomIndex = ValueNotifier(0);



  static const String createAccount = 'Hello!\nSignup to\nget started ';
  static const String login = 'Hello Again!\nWelcome\nback  ';
  static const String firstName = 'First Name';
  static const String lastName = 'Last Name';
  static const String email = 'Email';
  static const String username = 'Username';
  static const String password = 'Password';
  static const String signUP = 'Sign up';
  static const String signIN = 'Sign in';
  static const String submitRequest = 'Submit Request';
  static const String safety = 'Safety';
  static const String onboarding = 'Onboarding';
  static const String editAddress = 'Edit Address';
  static const String houseNameNumber = 'House name/number';
  static const String road = 'Road';
  static const String town = 'Town';
  static const String country = 'Country';
  static const String postCode = 'PostCode';
  static const String tools = 'Tools';
  static const String calender = 'Calender';
  static const String jennyWilson = 'Jenny Wilson';
  static const String home = 'Home';
  static const String requested = 'Requested';
  static const String approved = 'Approved';
  static const String rejected = 'Rejected';
  static const String leave = 'Leave';
  static const String save = 'Save';
  static const String saveAddress = 'Save Address';
  static const String signature = 'Signature';
  static const String notifications = 'Notifications';
  static const String holidayApproved = "Holiday Approved";
  static const String holiday = "Holiday";
  static const String contact = "Contact";
  static const String gasRateCal = "Gas Rate cal...";
  static const String processes = "Processes";
  static const String businessIncome = "Business income: ";
  static const String declaration = "Declaration - ";
  static const String description = "We are happy to grant your leave request for September 16 through 18.";
  static const String alreadyHaveAnAccount = 'Already Have An Account?   ';
  static const String doNtHaveAnAccount = 'Don’t have an account?   ';
  static const String typeCharge = 'Charge Type';
  static const String selectSize = 'Select size';
  static const String yes = 'Yes';
  static const String edit = 'Edit';
  static const String businessAddress = 'Business Address';
  static const String directorsName = 'Directors Name';
  static const String weight = 'Weight';
  static const String update = 'Update';
  static const String homeAddress = 'Homes Address (if different\nto business):';
  static const String contactTelephoneNumber = 'Contact Telephone Number';
  static const String emailAddress  = 'Email Address';
  static const String companyRegistrationNumber  = 'Company Registration Number(If\nApplicable)';
  static const String vatNumber = 'Vat Number: (If Applicable)';
  static const String nationalInsuranceNumber = 'National Insurance Number:';
  static const String poloJumperSize = 'Polo / Jumper size: ';
  static const String documentsRequired = 'Documents Required: (Please Upload)';
  static const String flueGasAnalyser= 'Flue gas analyser certificate or receipt if\nnew';
  static const String gasAccreditationCertificates= 'Gas accreditation certificates';
  static const String drivingLicenceFront = 'Driving Licence (Front)';
  static const String drivingLicenceBack= 'Driving Licence (Back)';
  static const String vanInsurance= 'Van insurance (Including business use)';
  static const String proofOfAddress= 'Proof of address dated within the last 2\nmonths (Bank statement, utility bill etc)';
  static const String passport= 'Passport (Picture page opened up like a\nbook)';
  static const String dBSCertificate= 'DBS Certificate';
  static const String publicLiabilityInsurance= 'Public Liability insurance - 5 million\nminimum cover';
  static const String addDocument= 'Add Document';
  static const String meterType = 'Meter Type';
  static const String selectMeterType = 'Select Meter Type';
  static const String fuelType = 'Fuel Type';
  static const String selectFuelType = 'Select Fuel Type';
  static const String start = 'Start';
  static const String stop = 'Stop';
  static const String reset = 'Reset';
  static const String meterReadingAtTheStart = 'Meter Reading at the Start';
  static const String testDialSize = 'Test Dial Size';
  static const String timeForOneRevolutionOfTestDial = 'Time for one Revolution of Test Dial';
  static const String enterLast3Digits = 'Enter last 3 digits';
  static const String meterReadingAtTheEnd = 'Meter Reading at the End';
  static const String timerValue = 'Timer value';
  static const String m = 'm';
  static const String s = 'S';
  static const String ft3 = 'ft3';
  static const String calculate = 'Calculate';
  static const String applianceHeatInput = 'Appliance Heat Input';
  static const String gross = 'Gross';
  static const String kW = 'kW';
  static const String mh = 'm3/h';
  static const String net = 'Net';
  static const String ddMmYy = 'dd-MM–yyyy';
  static const String ddMmYyy = 'yyyy-MM-d';
  static const String ddMmHhMmA = 'dd/MM – hh:mm a';
  static const String dMMMyHA = "d - MMM- y | h a";
  static const String yMMMdForMate = 'yMMMd';
  static const String signUPSuccess = "SignUp success!";
  static const String loginSuccess = "Login success!";
  static const String loginFailed = "Login failed!";
  static const String delete = "Delete";
  static const String plzEnterPWD = 'Please enter Password';
  static const String pWDRegExp = r'^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[!@#\$&*~]).{8,}$';
  // static const String pWDMustBeUpperLower = 'Password must be Uppercase,Lowercase,digit and specialCharacters';
  static const String pWDMustBeUpperLower = 'Password must be Eight Characters';

}
